language: ruby
rvm:
  - 1.9.3
  - 2.0.0
gemfile:
  - Gemfile
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: bundle exec rake spec
branches:
  only:
    - master
notifications:
  mails:
    - i2bskn@gmail.com